config/routes.rb
CaptionApp::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'static_pages#home'

 	resources :users do
 		member do
 			get :show_user_photos
 		end
 	end

  resources :photos do
  	member do
  		get :show_file
  		get :new_share_email
  		post :send_share_email
  	end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption, :file, :user_id

  validates :user_id, presence: true

  validate :file_size_validation, :if => "file?"  

  def file_size_validation
    errors[:file] << "should be less than 1MB" if file.size > 1.megabytes
  end

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # REV: do not use tabstops; you need to indent with spaces
  # REV: I wouldn't have stored the binary data in the `User`;
  # typically a photo is very large and should be stored in its own
  # table so that it isn't fetched with the rest of the object.
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  								:name, :profile_pic

  validates :name, presence: true

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include ApplicationHelper
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!, except: [:show, :show_file]

	def new
		@photo = Photo.new
	end

	def create
		file = params[:photo].delete(:file).read

		@photo = Photo.new(params[:photo])
		@photo.file = file

		if @photo.save
			flash[:success] = "Your photo has been successfully uploaded!"
			redirect_to @photo
		else
			flash[:error] = "Well, that didn't work! Care to try again? (Your file might be too big)"
			render 'new'
		end
	end

	def show
		@photo = Photo.find(params[:id])
		@captions = CAPTIONS
	end

	def show_file
		photo = Photo.find(params[:id])
		send_data(photo.file, type: 'image/jpg', disposition: 'inline')
	end

	def update
		photo = Photo.find(params[:id])
		photo.caption = params[:caption]

		if photo.save
			render nothing: true
		else
			flash[:error] = "That didn't save :( Try clicking the button again!"
			render 'new'
		end
	end

	def new_share_email
		@photo = Photo.find(params[:id])
	end

	def send_share_email
		@photo = Photo.find(params[:id])
		PhotoMailer.share_photo(params[:photo][:email], current_user.name , @photo).deliver

		redirect_to current_user
	end

	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy

		redirect_to current_user
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def new
		@user = User.new
	end

  def create
  	@user = User.new(params[:user])

  	if @user.save
  		flash[:success] = "Your account has been created!"
  		sign_in @user
  		redirect_to @user
  	else
  		flash[:error] = "That didn't work! Try again?"
  		render 'new'
  	end
  end

  def edit
  	@user = User.find_by_id(current_user.id)
  end

  def update
  	@user = User.find_by_id(current_user.id)

  	if @user.update_attributes(params[:user])
  		flash[:success] = "Yay! Your account has been updated!"
  		redirect_to @user
  	else
  		flash[:error] = "That didn't work very well... Care to try again?"
  		render 'edit'
  	end
  end


  def index
  	super
  end

  def destroy
  	super
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
    @photos = Photo.select("photos.*").order("updated_at DESC").limit(5)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def show
		@user = User.find(params[:id])
		@photos = @user.photos
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  CAPTIONS = ["This caption isn't funny.",
              "I'm hungry for cookies.",
              "Future heart breaker",
              "Thug lyfe",
              "Are you as bored as I am?",
              "Who do you think you are?",
              "Friends for life.",
              "Never met a mirror that I didn't like.",
              "Don't worry, I can handle this.",
              "I don't get most jokes, but I laugh anyways.",
              "#WINNING",
              "Don't worry, I know what I'm doing.",
              "Only you know what is on my mind.",
              "I'm your brother.",
              "All the single ladies",
              "Hey I just met you, and this is crazy...",
              "It's hard being this beautiful.",
              "Realy ridiculously good looking.",
              "Does this make my butt look big?",
              "Life is short.  Eat dessert before dinner.",
              "This is how my last hospital visit began...",
              "I prefer large posteriors and I cannot fib.",
              "I'm not a hipster.",
              "My diet starts tomorrow."]
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_header.html.erb
<div class="navbar">
	<div class="home-button">
		<%= link_to "Home", root_path %>
	</div>
	<ul class="navbar-buttons">
		<% if current_user.nil? %>
			<li><%= link_to "Sign In", new_user_session_path %></li>
			<li><%= link_to "Sign Up", new_user_registration_path %></li>
		<% else %>
			<li><%= link_to "Profile", user_path(current_user) %></li>
			<li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
			<li><%= link_to "Upload a Picture", new_photo_path %></li>
			<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caption Me!</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render '/layouts/header' %>

  <div class="body-wrap">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <% end %>

  	<%= yield %>
  </div>

</body>
</html>

app/views/photos/_file.html.erb
<div class="captioned-photo" data-photo-id="<%=file.id%>">
  <%= image_tag show_file_photo_url(file) %>
  <div class="photo-caption">
    <p><%= file.caption =></p>
  </div>
  <p>EDIT</p>
</div>

app/views/photos/new.html.erb
<h1>Upload a photo, add a caption, and instantly share friends!</h1>

<div class="upload-photo-form">

  <p>max photo size 1MB</p>

  <%= simple_form_for(@photo) do |f| %>

    <div class="file-field">
    	<%= f.file_field :file %>
    </div>

  	<%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id } %>

    <div class="form-actions">
      <%= f.button :submit, "Upload!" %>
    </div>

  <% end %>
</div>

app/views/photos/new_share_email.html.erb
<h1>Email your photo!</h1>

<div class="share-photo-form">
  <%= simple_form_for(@photo, url: send_share_email_photo_path(@photo), method: :post) do |f| %>
    <div class="form-inputs">
    	<%= f.input :email, input_html: { value: '' } %>
    </div>
    <div class="form-actions">
    	<%= f.submit "Share!" %>
    </div>
  <% end %>
</div>

<br>
<hr>

<h1>Tweet your photo!</h1>

<a href="https://twitter.com/share" class="twitter-share-button" data-count="none" data-size="large"data-lang="en" data-text="<%= @photo.caption %>" data-url="http://limitless-river-8895.herokuapp.com/photos/<%=@photo.id%>">Tweet!</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/photos/show.html.erb
<% if current_user %>
	<% if @photo.user_id == current_user.id %>

		<h1>Add a caption, then share!</h1>

		<div class="photo-to-edit">
			<%= image_tag show_file_photo_url(@photo.id)%>
		</div>
		
		<div class="photo-caption">
			<p><%=@photo.caption%></p>
		</div>

		<div class="caption-share-buttons">
			<button class="random-caption-button" data-caption="<%= @captions.to_json %>" data-photo-id="<%= @photo.id %>">Caption this photo!
			</button>

			<div class="delete-button">
				<%= link_to image_tag("trash-can.png"), photo_url(@photo), method: :delete,
						confirm: "Are you sure you want to delete this photo?" %>
			</div>

			<div class="share-button">
				<%= link_to "Share!", new_share_email_photo_url(@photo.id) %>
			</div>

		</div>

			<script type="text/javascript">

		 	$(function() {

		 		$('.random-caption-button').click(function() {
		 			var captions = $(this).data('caption');
		 			var photo_id = $(this).attr('data-photo-id');
		 			var rand_num = Math.floor(Math.random() * captions.length);
		 			var rand_caption = captions[rand_num];

		 			$.post(
		 				'/photos/' + photo_id,
		 				{ id: photo_id, caption: rand_caption, "_method":"put" },
		 				function() {
		 					var caption = $('.photo-caption').children();
		 					caption.empty();
				 			caption.append(rand_caption);
		 				}
		 			);
		 		});
		 	});

		</script>

	<% else %>

		<h1><%= link_to("#{@photo.user.name}", user_path(@photo.user_id)) %>'s Photo</h1>

		<div class="photo-to-edit">
			<%= image_tag show_file_photo_url(@photo.id)%>
		</div>
		
		<div class="photo-caption">
			<p><%=@photo.caption%></p>
		</div>

	<% end %>

<% else %>

	<div class="photo-to-edit">
		<%= image_tag show_file_photo_url(@photo.id)%>
	</div>
	
	<div class="photo-caption">
		<p><%=@photo.caption%></p>
	</div>

<% end %>

app/views/static_pages/home.html.erb
<%#= stylesheet_link_tag "modern.css" %>
<%#= javascript_include_tag "carousel.js" %>

<h1>Welcome!</h1><br>

<% if current_user %>

  <div class="carousel" data-role="carousel" data-param-period="4000">
    <div class="slides">
      <% @photos.each do |photo| %>
        <div class="slide image">
            <%= image_tag show_file_photo_path(photo) %>
            <div class="description">
                <%= photo.caption %>
            </div>
        </div>
      <% end %>
    </div>

    <span class="control left">‹</span>
    <span class="control right">›</span>
  </div>

<% else %>
  <h2 class="front-page-text">
    Have you ever taken the perfect picture, but not been able to come up
    with a caption for it? If so, then this site is for you! Our
    highly advanced randomizing technology will help you find the perfect
    caption for your picture. Sign up today!
  </h2>
<% end %>

app/views/users/show.html.erb
<div id="profile-header">
  <h1><%= @user.name %>'s photos!</h1>
</div>

<hr>

<% if @photos.empty? && @user.id == current_user.id %>
  <h3>You don't have any photos yet :( Use the button up top to fill our your profile!</h3>
<% elsif @photos.empty? && @user.id != current_user.id %>
  <h3><%= @user.name %> doesn't seem to have any photos yet :(</h3>
<% else %>
  <% @photos.each do |photo| %>
    <div class="captioned-photo" data-photo-id="<%=photo.id%>">
      <%= image_tag show_file_photo_url(photo) %>
      <div class="photo-caption">
        <p><%= photo.caption %></p>
      </div>
    </div>
    <hr>
    <br>
  <% end %>
<% end  %>

<!-- Makes photos clickable -->
<script type="text/javascript">

	$(function() {
		$('.captioned-photo').click(function() {
			var photo_id = $(this).data('photo-id');
      window.location = '/photos/' + photo_id;
		});
  });

</script>